### ISSUE TITLE
compile.m fails

### ISSUE THREAD

**Issue by ZhouYzzz** [rksltnl/Deep-Metric-Learning-CVPR16#1]
When running modified **compile.m**, error occurs that:

```
path/to/serialized_pairs_to_leveldb.cpp:14:22: fatal error: caffe.pb.h: No such file or directory
 #include "caffe.pb.h"
                      ^
compilation terminated.
```

And change `-L/path/to/caffe/build/src/caffe/proto` tag to `-I/path/to/caffe/build/src/caffe/proto` will find `"caffe.pb.h"`, and it works.

Besides, `imageset_to_leveldb.cpp` to compile is lost, have you changed its name to `serialized_triplets_to_leveldb.cpp`?

**Comment by yuxng** [comment]
imageset_to_leveldb.cpp has been added.
The compile.m has been fixed. Please do "git pull".

**Comment by rksltnl** [comment]
closing.
