### ISSUE TITLE
GIF's in the Ebay dataset

### ISSUE THREAD

**Issue by vadimkantorov** [rksltnl/Deep-Metric-Learning-CVPR16#10]
Hi,
It happens there're 6 GIF's in the dataset that confuses other languages trying to decompress a JPEG:

```
data/Stanford_Online_Products/lamp_final/271802113987_2.JPG GIF 400x400 400x400+0+0 8-bit sRGB 256c 57KB 0.000u 0:00.000
data/Stanford_Online_Products/lamp_final/221777566426_7.JPG GIF 400x400 400x400+0+0 8-bit sRGB 256c 93.3KB 0.000u 0:00.000
data/Stanford_Online_Products/fan_final/280961317122_7.JPG GIF 167x400 167x400+0+0 8-bit sRGB 256c 31.7KB 0.000u 0:00.000
data/Stanford_Online_Products/fan_final/131546166499_5.JPG GIF 500x500 500x500+0+0 8-bit sRGB 256c 59.4KB 0.000u 0:00.000
data/Stanford_Online_Products/coffee_maker_final/291488772961_1.JPG GIF 500x500 500x500+0+0 8-bit sRGB 256c 80.9KB 0.000u 0:00.000
data/Stanford_Online_Products/bicycle_final/231588927256_1.JPG GIF 400x250 400x250+0+0 8-bit sRGB 256c 47.6KB 0.000u 0:00.000
```

I'll convert these using ImageMagick, but to avoid surprises of future users of the dataset, it might be beneficial to update the distributed zip file.

**Comment by rksltnl** [comment]
@yuxng Yu, if I convert the faulty images and give them to you, can you update the tar file in the ftp?

**Comment by yuxng** [comment]
Sure, I will update the tar file.

**Comment by rksltnl** [comment]
@yuxng 

[converted_images.tar.gz](https://github.com/rksltnl/Deep-Metric-Learning-CVPR16/files/604707/converted_images.tar.gz)

Please update the tar file with these images.

Thanks.

**Comment by rksltnl** [comment]
@yuxng ping

**Comment by yuxng** [comment]
The zip file has been updated.

Best,
Yu
