### ISSUE TITLE
why there is no GPU implementation of this loss layer?

### ISSUE THREAD

**Issue by nanoart** [rksltnl/Deep-Metric-Learning-CVPR16#12]
I don't see the GPU implementation of this loss layer in caffe submodule.  Just wonder why.

Many thanks,

**Comment by rksltnl** [comment]
Hi. We benchmarked the forward-backward time it takes per each layer. The loss layer (currently implemented in CPU) accounted for less than 1% of the total forward-backward time. Basically, the bottleneck is in the convolution layers so there wasn't any need for fast GPU version of the loss layer.
