### ISSUE TITLE
run the compile.m failed

### ISSUE THREAD

**Issue by dldl3D** [rksltnl/Deep-Metric-Learning-CVPR16#13]
When running modified compile.m, the errors are as follows:
![error](https://cloud.githubusercontent.com/assets/8369046/20597397/54d4f748-b27e-11e6-9afa-fd7a82c58ceb.png)

The caffe has been installed correctly. How can I solved this problem?

Thanks.

**Comment by gavinmh** [comment]
@YuetianLiu can you share how you fixed this?

**Comment by xingener** [comment]
@YuetianLiu Hav the same error...

**Comment by rksltnl** [comment]
Install the submodule version of Caffe not the latest one.
If you got a working version of compile.m that works with the current Caffe version, please do a pull request.
