### ISSUE TITLE
gen_caffe_dataset_multilabel_m128.m run error

### ISSUE THREAD

**Issue by yja1** [rksltnl/Deep-Metric-Learning-CVPR16#15]
执行gen_caffe_dataset_multilabel_m128.m 的时候报错：
Deleted 31 data pairs from negatives for batch divisibility
Writing level db..
Invalid MEX-file '/home/yja/caffecode/lifted_caffe/code/serialized_pairs_to_leveldb.mexa64':
libcaffe.so.1.0.0-rc3: cannot open shared object file: No such file or directory
Error in gen_caffe_dataset_multilabel_m128 (line 88)
但是已经做了compile.m  生成了serialized_pairs_to_leveldb.mexa64。希望您帮看下，谢谢！

**Comment by AshutoshMI777** [comment]
How did you solve the issue? @yja1

**Comment by Ashutosh1995** [comment]
How did you solve the issue? @yja1

**Comment by yja1** [comment]
在同目录下做一个libcaffe的软连接 
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Ashutosh Mishra";<notifications@github.com>;
 发送时间: 2017年7月26日(星期三) 下午4:19
 收件人: "rksltnl/Deep-Metric-Learning-CVPR16"<Deep-Metric-Learning-CVPR16@noreply.github.com>; 
 抄送: "1094110236"<1094110236@qq.com>; "Mention"<mention@noreply.github.com>; 
 主题: Re: [rksltnl/Deep-Metric-Learning-CVPR16]gen_caffe_dataset_multilabel_m128.m run error (#15)

 

 
How did you solve the issue? @yja1

**Comment by Ashutosh1995** [comment]
Can you please write it in english?

**Comment by yja1** [comment]
make a link for libcaffe.so in the same folder with gen_caffe_dataset_multilabel_m128.m
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Ashutosh Mishra";<notifications@github.com>;
 发送时间: 2017年7月26日(星期三) 下午5:16
 收件人: "rksltnl/Deep-Metric-Learning-CVPR16"<Deep-Metric-Learning-CVPR16@noreply.github.com>; 
 抄送: "1094110236"<1094110236@qq.com>; "Mention"<mention@noreply.github.com>; 
 主题: Re: [rksltnl/Deep-Metric-Learning-CVPR16]gen_caffe_dataset_multilabel_m128.m run error (#15)

 

 
Can you please write it in english?

**Comment by Ashutosh1995** [comment]
Libcaffe.so is in the caffe directory i.e. /caffe/build/lib and the gen_caffe_dataset_multilabel_m128.m matlab code is in code directory of the project. Could you please elaborate more as to how to make the link?

**Comment by yja1** [comment]
or you can copy libcaffe.so.1.0.0-rc3 (in the caffe directory) to 
  gen_caffe_dataset_multilabel_m128.m folder

 

 ------------------ 原始邮件 ------------------
  发件人: "Ashutosh Mishra";<notifications@github.com>;
 发送时间: 2017年7月26日(星期三) 下午5:30
 收件人: "rksltnl/Deep-Metric-Learning-CVPR16"<Deep-Metric-Learning-CVPR16@noreply.github.com>; 
 抄送: "1094110236"<1094110236@qq.com>; "Mention"<mention@noreply.github.com>; 
 主题: Re: [rksltnl/Deep-Metric-Learning-CVPR16]gen_caffe_dataset_multilabel_m128.m run error (#15)

 

 
Libcaffe.so is in the caffe directory i.e. /caffe/build/lib and the gen_caffe_dataset_multilabel_m128.m code is in code directory of the project. Could you please elaborate more as to how to make the link?

**Comment by Ashutosh1995** [comment]
I copied libcaffe.so in the folder containing the gen_caffe_dataset_multilabel_m128.m code but it gives the following error:

Invalid MEX-file '/users/amishra/code/serialized_pairs_to_leveldb.mexa64':
/users/amishra/caffe/caffe-master/build/lib/libcaffe.so.1.0.0: undefined
symbol:_ZN2cv8imencodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11_InputArrayERSt6vectorIhSaIhEERKSB_IiSaIiEE

**Comment by yja1** [comment]
copy libcaffe.so.1.0.0-rc3 not libcaffe.so. 
 and run in .m file folder: ln -s libcaffe.so.1.0.0-rc3 libcaffe.so
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Ashutosh Mishra";<notifications@github.com>;
 发送时间: 2017年7月26日(星期三) 晚上6:02
 收件人: "rksltnl/Deep-Metric-Learning-CVPR16"<Deep-Metric-Learning-CVPR16@noreply.github.com>; 
 抄送: "1094110236"<1094110236@qq.com>; "Mention"<mention@noreply.github.com>; 
 主题: Re: [rksltnl/Deep-Metric-Learning-CVPR16]gen_caffe_dataset_multilabel_m128.m run error (#15)

 

 
I copied libcaffe.so in the folder containing the gen_caffe_dataset_multilabel_m128.m code but it gives the following error:
 
Invalid MEX-file '/users/amishra/code/serialized_pairs_to_leveldb.mexa64':
/users/amishra/caffe/caffe-master/build/lib/libcaffe.so.1.0.0: undefined
symbol:_ZN2cv8imencodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11_InputArrayERSt6vectorIhSaIhEERKSB_IiSaIiEE

**Comment by Ashutosh1995** [comment]
I did but after executing the command libcaffe.so pops up and I get the same error as before.

**Comment by yja1** [comment]
you can try this, in .m file folder run: 
 rm libcaffe.so  
 ln -s libcaffe.so.1.0.0-rc3 /users/amishra/caffe/caffe-master/build/lib/libcaffe.so
  ln -s libcaffe.so.1.0.0-rc3 /users/amishra/caffe/caffe-master/build/lib/libcaffe.so.1.0.0 
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Ashutosh Mishra";<notifications@github.com>;
 发送时间: 2017年7月26日(星期三) 晚上7:04
 收件人: "rksltnl/Deep-Metric-Learning-CVPR16"<Deep-Metric-Learning-CVPR16@noreply.github.com>; 
 抄送: "1094110236"<1094110236@qq.com>; "Mention"<mention@noreply.github.com>; 
 主题: Re: [rksltnl/Deep-Metric-Learning-CVPR16]gen_caffe_dataset_multilabel_m128.m run error (#15)

 

 
I did but after executing the command libcaffe.so pops up and I get the same error as before.

**Comment by Ashutosh1995** [comment]
I did it and it says:

ln: failed to create symbolic link '/users/amishra/caffe/caffe-master/build/lib/libcaffe.so.1.0.0': File exists

**Comment by yja1** [comment]
can you show you folder files of gen_caffe_dataset_multilabel_m128.m 

  

 ------------------ 原始邮件 ------------------
  发件人: "Ashutosh Mishra";<notifications@github.com>;
 发送时间: 2017年7月26日(星期三) 晚上7:14
 收件人: "rksltnl/Deep-Metric-Learning-CVPR16"<Deep-Metric-Learning-CVPR16@noreply.github.com>; 
 抄送: "1094110236"<1094110236@qq.com>; "Mention"<mention@noreply.github.com>; 
 主题: Re: [rksltnl/Deep-Metric-Learning-CVPR16]gen_caffe_dataset_multilabel_m128.m run error (#15)

 

 
I did it and it says:
 
ln: failed to create symbolic link '/users/amishra/caffe/caffe-master/build/lib/libcaffe.so.1.0.0': File exists

**Comment by Ashutosh1995** [comment]
These are the files in the folder containing the matlab code of gen_caffe_multilabel_m128.m

128.py
config.m
evaluation
find_dups.m
gen_caffe_dataset_multilabel_m128.m
gen_caffe_validation_imageset.m
gen_images.m
gen_splits.m
get_training_examples_multilabel.m
IIITCFWdata.mat
imageset_to_leveldb.cpp
imageset_to_leveldb.mexa64
libcaffe.so.1.0.0-rc3
load_cropped_images.m
queryInfo.mat
realFaces
savefast.m
serialized_pairs_to_leveldb.cpp
serialized_pairs_to_leveldb.mexa64
serialized_triplets_to_leveldb.cpp
splits.mat
training_images_crop15_square256.mat
validation_images_crop15_square256.mat

**Comment by yja1** [comment]
sorry, run this:
  rm libcaffe.so  
 ln -s  /users/amishra/caffe/caffe-master/build/lib/libcaffe.so.1.0.0-rc3  libcaffe.so
 ln -s  /users/amishra/caffe/caffe-master/build/lib/libcaffe.so.1.0.0-rc3 libcaffe.so.1.0.0
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Ashutosh Mishra";<notifications@github.com>;
 发送时间: 2017年7月26日(星期三) 晚上7:25
 收件人: "rksltnl/Deep-Metric-Learning-CVPR16"<Deep-Metric-Learning-CVPR16@noreply.github.com>; 
 抄送: "1094110236"<1094110236@qq.com>; "Mention"<mention@noreply.github.com>; 
 主题: Re: [rksltnl/Deep-Metric-Learning-CVPR16]gen_caffe_dataset_multilabel_m128.m run error (#15)

 

 
These are the files in the folder containing the matlab code of gen_caffe_multilabel_m128.m
 
128.py
config.m
evaluation
find_dups.m
gen_caffe_dataset_multilabel_m128.m
gen_caffe_validation_imageset.m
gen_images.m
gen_splits.m
get_training_examples_multilabel.m
IIITCFWdata.mat
imageset_to_leveldb.cpp
imageset_to_leveldb.mexa64
libcaffe.so.1.0.0-rc3
load_cropped_images.m
queryInfo.mat
realFaces
savefast.m
serialized_pairs_to_leveldb.cpp
serialized_pairs_to_leveldb.mexa64
serialized_triplets_to_leveldb.cpp
splits.mat
training_images_crop15_square256.mat
validation_images_crop15_square256.mat

**Comment by Ashutosh1995** [comment]
I did exactly what you said but the error still not goes, rather now it is:

Invalid MEX-file '/users/amishra/code/serialized_pairs_to_leveldb.mexa64':
libcaffe.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by Ashutosh1995** [comment]
Hey @yja1 @rksltnl , please suggest some alternative to this error

The reason it gives error I think because both the .so files are in the same folder.

Do they need to be in the same or what needs to be done?

**Comment by rksltnl** [comment]
Did you follow the [Caffe installation instructions](http://caffe.berkeleyvision.org/installation.html)?
Are Pycaffe and Matcaffe installed?

**Comment by Ashutosh1995** [comment]
Yes I have installed caffe according to the instructions given on the CAFFE page

**Comment by rksltnl** [comment]
Which version of Caffe? Did you install the included submodule version? https://github.com/rksltnl/Caffe-Deep-Metric-Learning-CVPR16

**Comment by Ashutosh1995** [comment]
No, I didn't install the submodule version. I am following the steps of training in the first part. Do I need to install it?

**Comment by rksltnl** [comment]
Yes it's possible that something got changed in recent Caffe and isn't compatible with the submodule version. Please try the submodule Caffe version.

**Comment by Ashutosh1995** [comment]
I figured out that matcaffe wasn't installed and it was a mistake on my part. After doing the necessary installations and re-checking it again, though I did not install the Caffe submodule version as it is giving some error to build, I get the same error **Invalid MEX file** error when following the basic installation steps

Please help me in this !!

**Comment by Ashutosh1995** [comment]
With which version of cuDNN have you compiled the submodule version as I have CUDA version 8 and cuDNN version 5.1.5 but it gives error in cudnn.hpp: error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"
