### ISSUE TITLE
math_functions.cu:375] Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE

### ISSUE THREAD

**Issue by yja1** [rksltnl/Deep-Metric-Learning-CVPR16#16]
math_functions.cu:375] Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE
I met this problem when train the model, do you know why.thanks!
I try another edition caffe, put the lift_struct_simality_softmaxloss layer into it, but the problem also

**Comment by Elena-ssq** [comment]
Hi, I'v met the same problem. Is the problem solved already?
