### ISSUE TITLE
GPU issue

### ISSUE THREAD

**Issue by pribadihcr** [rksltnl/Deep-Metric-Learning-CVPR16#2]
Hi

I got the following error when compile caffe using CPU mode only:
 STUB_GPU(LiftedStructSimilaritySoftmaxLossLayer);
 ^
make: **\* [.build_release/src/caffe/layers/lifted_struct_similarity_softmax_layer.o] Error 1

Is there only GPU mode ?

Thanks

**Comment by rksltnl** [comment]
Hi pribadihcr,

Can you comment out lines from L209 to L211 in src/caffe/layers/lifted_struct_similarity_softmax_layer.cpp,  recompile, and report back the result here?

https://github.com/rksltnl/Caffe-Deep-Metric-Learning-CVPR16/blob/0efd7544a9846f58df923c8b992198ba5c355454/src/caffe/layers/lifted_struct_similarity_softmax_layer.cpp#L209-211

**Comment by pribadihcr** [comment]
Hi @rksltnl 

Its work. Thanks

**Comment by rksltnl** [comment]
I commented it out on the repository as well. Closing.
