### ISSUE TITLE
why shift the cost for negative samples before applying exponent?

### ISSUE THREAD

**Issue by patzm** [rksltnl/Deep-Metric-Learning-CVPR16#24]
Hi there,
in [lines 127 to 131 in your loss layer implementation](https://github.com/rksltnl/Caffe-Deep-Metric-Learning-CVPR16/blob/0efd7544a9846f58df923c8b992198ba5c355454/src/caffe/layers/lifted_struct_similarity_softmax_layer.cpp#L127) you calculate the argument of the exponent in

![equation 4](https://user-images.githubusercontent.com/5219726/30387961-7d66e074-98ae-11e7-87e0-73374f678151.png)
```c++
Dtype max_elem = *std::max_element(loss_aug_inference_.cpu_data(), loss_aug_inference_.cpu_data() + num_negatives);
caffe_add_scalar(loss_aug_inference_.count(),
    Dtype(-1.0)*max_elem, // shift
    loss_aug_inference_.mutable_cpu_data());
caffe_exp(loss_aug_inference_.count(), loss_aug_inference_.mutable_cpu_data(), loss_aug_inference_.mutable_cpu_data());
Dtype soft_maximum = log(caffe_cpu_dot(num_negatives, summer_vec_.cpu_data(), loss_aug_inference_.mutable_cpu_data()))
    + max_elem; // shift back
```
However, you shift it by the maximum element of ![codecogseqn 1](https://user-images.githubusercontent.com/5219726/30388053-cc8b10da-98ae-11e7-9fd3-574135c10f67.png) such that it is in the range [-inf, 0] when applying the exponent. Later, in line 131, you shift it back after applying the logarithm. I can not find any mentioning of this in your paper.

Could you please elaborate on this?

**Comment by rksltnl** [comment]
[link](https://hips.seas.harvard.edu/blog/2013/01/09/computing-log-sum-exp/)
It's for numerical stability.
