### ISSUE TITLE
For training, is't necessary to normalize the feature before LiftedStructSimilaritySoftmaxLoss layer?

### ISSUE THREAD

**Issue by ysc703** [rksltnl/Deep-Metric-Learning-CVPR16#25]
Hi @rksltnl ,
I am trying to use this method to my own datasets again.
When doing net forward at LiftedStructSimilaritySoftmaxLoss layer, the distance of two sample is ||**X**_i_ - **X**_j_ ||2. I think it may be bigger than the margin sometimes, is right?
And is't necessary to normalize the feature before this layer?

Thank you!

**Comment by rksltnl** [comment]
No, it's unnecessary to normalize the feature before the loss layer.
