### ISSUE TITLE
Invalid MEX-file '/home/rpk/caffe_set/Deep-Metric-Learning-CVPR16/Caffe-Deep-Metric-Learning-CVPR16/matlab/code/serialized_pairs_to_leveldb.mexa64': libcaffe.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by camel007** [rksltnl/Deep-Metric-Learning-CVPR16#8]
getenv('LD_LIBRARY_PATH')
/usr/local/MATLAB/R2014b/sys/os/glnxa64:/usr/local/MATLAB/R2014b/bin/glnxa64:/usr/local/MATLAB/R2014b/extern/lib/glnxa64:/usr/local/MATLAB/R2014b/runtime/glnxa64:/usr/local/MATLAB/R2014b/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/usr/local/MATLAB/R2014b/sys/java/jre/glnxa64/jre/lib/amd64/server:/home/rpk/caffe_set/Deep-Metric-Learning-CVPR16/Caffe-Deep-Metric-Learning-CVPR16/.build_release/lib

**Comment by nikoong** [comment]
I have met the same problem, did you solve this? @camel007

**Comment by rksltnl** [comment]
Did you compile it?

**Comment by camel007** [comment]
Thanks a lot!
Yes, I got "caffe_.mexa64"  in "matlab/+caffe/private/"
and "libcaffe.so.1.0.0-rc3" in "./build_release/lib"

**Comment by rksltnl** [comment]
It's all in the README. Please read the README file before opening issues.

**Comment by EhsanEI** [comment]
I have the same issue. I have compiled the module and followed the README file.
"./build_release/lib" is in my LD_LIBRARY_PATH and LD_RUN_PATH.
But still I get this error.

**Comment by rksltnl** [comment]
Make sure run the compile script as mentioned in the README and your LD_LIBRARY_PATH is set correctly in your bash script.
export LD_LIBRARY_PATH=/path/to/caffe/build/lib:$LD_LIBRARY_PATH

**Comment by dldl3D** [comment]
Hi, I have the same problem. I have run the compile.m, generated the imageset_to_leveldb.mexa64 and serialized_pairs_to_leveldb.mexa64 dile. But when I run the gen_caffe_dataset_multilabel_m128.m,  I get this error. I have set my LD_LIBRARY_PATH. @camel007 @rksltnl

**Comment by AshutoshMI777** [comment]
I am also facing the same error. I exported the LD_LIBRARY_PATH to the path where the caffe libcaffe.so file is located i.e. the build/lib directory and checked it with Matlab also using the command **getenv('LD_LIBRARY_PATH')**. Both the commands displays the same library path where the libcaffe.so is stored but still it pops up the error: 

Invalid MEX file  undefined
symbol:_ZN2cv8imencodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11_InputArrayERSt6vectorIhSaIhEERKSB_IiSaIiEE

**Comment by Ashutosh1995** [comment]
I am also getting the same error. I have exported the LD_LIBRARY_PATH to the same lib folder in the caffe i.e. /caffe/build/lib etc and followed the README.md but I am getting the error like: 

Invalid MEX-file '/users/amishra/code/serialized_pairs_to_leveldb.mexa64':
/users/amishra/caffe/caffe-master/build/lib/libcaffe.so.1.0.0: undefined
symbol:_ZN2cv8imencodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11_InputArrayERSt6vectorIhSaIhEERKSB_IiSaIiEE

Can anyone help me on this?

**Comment by wang5566** [comment]
I compiled cpp successfully.But i got the same error "libcaffe.so: cannot open shared object file: No such file or directory". I am sure to setenv LD_LIBRARY_PATH with my caffe/build/lib, any help can be appreciated.
